document.getElementById('downloadBtn').addEventListener('click', function () {
    // Get form data
    const name = document.getElementById('name').value;
    const email = document.getElementById('email').value;
    const address = document.getElementById('address').value;
    const dob = document.getElementById('dob').value;
    const autoGeneratedID = document.getElementById('autoGeneratedID').value;
    const state = document.getElementById('state').value;
    const state1 = document.getElementById('state1').value;
    const dob1 = document.getElementById('dob1').value;
    const dob2 = document.getElementById('dob2').value;
    const Photo = document.getElementById('Photo').value;
	
	

    // Create a new HTML page content
    const outputHTML = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Form Output</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    padding: 20px;
                }
                h1 {
                    text-align: center;
                }
                .output {
                    border: 2px solid #ddd;
                    padding: 20px;
                    max-width: 600px;
                    margin: 0 auto;
					backgroundColor:pink;
                }
            </style>
        </head>
        <body>
            <h1>MST FORM</h1>
            <div class="output">
                <p><strong>Name:</strong> ${name}</p>
                <p><strong>Email:</strong> ${email}</p>
                <p><strong>D.O.B:</strong> ${dob}</p>
				<p><strong>Address:</strong> ${address}</p>
                <p><strong>Receipt No:</strong> ${autoGeneratedID}</p>
                <p><strong>Routes</strong></p>
                <p><strong>From:</strong> ${state}</p>
                <p><strong>To:</strong> ${state1}</p>
                <p><strong>Valid Till:</strong> ${dob1}</p>
                <p><strong>To:</strong> ${dob2}</p>
                <p><strong>Uploaded Photo:</strong><img src "${Photo}"></p>
            </div>
        </body>
        </html>
    `;

    // Create a Blob with the output HTML content
    const blob = new Blob([outputHTML], { type: 'text/html' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'form_output.html';
    
    // Trigger the download
    link.click();
});